export const TRAILS = [
    {
        id: 0,
        name:"Sol Duc Falls Nature Trail",
        season: "Spring",
        level: "Easy",
        distance: "1.6 miles",
        elevation: "255 feet",         
        image:"/assets/images/trails/spring-easy-sol-duc-trail.png",
        photographer:"Paul Nguyen",
        Source: "AllTrails",
        featured: false
    },
    {
        id: 1,
        name: "Dalles Moutain Trail",
        season: "Spring",
        level: "Moderate",
        distance: "10.6 miles",
        elevation: "2,355 feet",         
        image: "/assets/images/trails/spring-moderate-dalles-mountain.png",
        photographer: "Nelli Zavalnyuk",
        Source: "AllTrails",
        featured: false
    },
    {
        id: 2,
        name: "Mount Si Trail",
        season: "Sring",
        level: "Hard",
        distance: "7.9 miles",
        elevation: "3,199 feet",         
        image: "/assets/images/trails/spring-hard-mt-si.png",
        photographer: "Josh Fortner",
        Source: "AllTrails",
        featured: false
    },
    {
        id: 3,
        name: "Naches Peak Loop Trail",
        season: "Summer",
        level: "Easy",
        distance: "3.3 miles",
        elevation: "636 feet",         
        image: "/assets/images/trails/summer-easy-naches-peak-loop.jpg",
        photographer:"Erika Weber",
        Source: "AllTrails",
        featured: false
    },
    {
        id: 4,
        name: "Tolmie Peak Trail",
        season: "Summer",
        level: "Moderate",
        distance: "6.4 miles",
        elevation: "1,522 feet",         
        image: "/assets/images/trails/summer-moderate-tolmie-peak.png",
        photographer:"Kaitlin Schoewe",
        Source: "AllTrails",
        featured: false
    },
    {
        id: 5,
        name: "Mount Pilchuck Trail",
        season: "Summer",
        level: "Hard",
        distance: "6.0 miles",
        elevation: "2,125 feet",         
        image: "/assets/images/trails/summer-hard-mt-pilchuck.png",
        photographer:"Madina A",
        Source: "AllTrails",
        featured: false
    },
    {
        id: 6,
        name: "Old Pipeline Bed Trail",
        season: "Fall",
        level: "Easy",
        distance: "2.4 miles",
        elevation: "85 feet",         
        image: "/assets/images/trails/fall-easy-old-pipeline-bed-trail.png",
        photographer:"Clark Llamzon",
        Source: "AllTrails",
        featured: false
    },
    {
        id: 7,
        name: "Rattlesnake Ledge Trail",
        season: "Fall",
        level: "Moderate",
        distance: "5.1 miles",
        elevation: "1,469 feet",         
        image: "/assets/images/trails/fall-moderate-rattlesnake-ledge-trail.png",
        photographer:"Brenda Borrows",
        Source: "AllTrails",
        featured: false
    },
    {
        id: 8,
        name: "Skyline Divide Trail",
        season: "Fall",
        level: "Hard",
        distance: "7.7 miles",
        elevation: "1,469 feet",         
        image: "/assets/images/trails/fall-hard-skyline-divide-trail.jpg",
        photographer:"Unknown",
        Source: "AllTrails",
        featured: false
    },
    {
        id: 9,
        name: "Big Four Ice Caves",
        season: "Winter",
        level: "Easy",
        distance: "3.2 miles",
        elevation: "489 feet",         
        image: "/assets/images/trails/winter-easy-big-four-ice-caves.png",
        photographer:"Thomas McElfresh",
        Source: "AllTrails",
        featured: false
    },
    {
        id: 10,
        name: "Wallace Falls Trail",
        season: "Winter",
        level: "Moderate",
        distance: "5.9 miles",
        elevation: "1,404 feet",         
        image: "/assets/images/trails/winter-moderate-wallace-falls-trail.jpg",
        photographer:"David Van Hove",
        Source: "AllTrails",
        featured: false
    },
    {
        id: 11,
        name: "Lake Serene Trail & Bridal Veil Falls",
        season: "Winter",
        level: "Hard",
        distance: "10.2 miles",
        elevation: "3,261 feet",         
        image: "/assets/images/trails/winter-hard-lake-serene.png",
        photographer:"Michael Uyehara",
        Source: "AllTrails",
        featured: false
    }
];